# Generated by Django 3.0.3 on 2020-04-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accidents_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=11, unique=True)),
                ('week_day', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=11)),
                ('time', models.CharField(max_length=5, null=True)),
                ('type_event', models.CharField(max_length=2)),
                ('phase', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('total_occupants', models.IntegerField(null=True)),
                ('total_fatalities', models.IntegerField(null=True)),
                ('aircraft_damage', models.CharField(max_length=100, null=True)),
                ('aircraft_fate', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iata', models.CharField(max_length=3, null=True)),
                ('code_icao', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='flight_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100, null=True)),
                ('nature', models.CharField(max_length=100, null=True)),
                ('flight_number', models.CharField(max_length=20, null=True)),
                ('crew_number', models.IntegerField(null=True)),
                ('passengers_number', models.IntegerField(null=True)),
                ('id_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliweb.accidents_events')),
            ],
        ),
        migrations.CreateModel(
            name='fatalities_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_fatalities', models.IntegerField(null=True)),
                ('passengers_fatalities', models.IntegerField(null=True)),
                ('collision_casualties', models.IntegerField(null=True)),
                ('ground_casualties', models.IntegerField(null=True)),
                ('id_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliweb.accidents_events')),
            ],
        ),
        migrations.CreateModel(
            name='destination_airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliweb.flight_info')),
                ('icao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appliweb.airports')),
            ],
        ),
        migrations.CreateModel(
            name='departure_airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliweb.flight_info')),
                ('icao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appliweb.airports')),
            ],
        ),
        migrations.CreateModel(
            name='aircrafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aircraft', models.CharField(max_length=100, null=True)),
                ('number_engines', models.IntegerField(null=True)),
                ('type_engines', models.CharField(max_length=100, null=True)),
                ('first_flight', models.IntegerField(null=True)),
                ('cycles', models.IntegerField(null=True)),
                ('total_airframe_hours', models.IntegerField(null=True)),
                ('registration', models.CharField(max_length=100, null=True)),
                ('c_n_msn', models.CharField(max_length=100, null=True)),
                ('id_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliweb.accidents_events')),
            ],
        ),
    ]
